# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZTFXIY2UH6nO9QTyNYU0g4RctGB0Yb3
"""

Name: koppoju Jejeeya
Reg No : 21BCE8280
Mobile No: 8500403814
Campus: VIT-AP

import seaborn as sns
print(sns.get_dataset_names())

df = sns.load_dataset('car_crashes')
df

x = df.head(5)
x

df.info()

sns.scatterplot(x="speeding",y="alcohol",data=df)

sns.scatterplot(x="total",y="no_previous",data=df)

sns.scatterplot(x="alcohol",y="not_distracted",data=df)

sns.scatterplot(x="total",y="alcohol",data=df)

sns.scatterplot(x='ins_premium',y='ins_losses',data=df)

sns.barplot(data=x,x="speeding",y="alcohol",ci=None)

sns.barplot(data=x,x="speeding",y="not_distracted",ci=None)

sns.barplot(data=x,x="total",y="alcohol",ci=None)

sns.barplot(data=df,x="not_distracted",y="total",ci=None)

sns.barplot(data=x,x="speeding",y="total",ci=None)

sns.lineplot(x='alcohol',y='total',data=df,ci=None)

sns.lineplot(x='alcohol',y='not_distracted',data=df,ci=None)

sns.lineplot(x='no_previous',y='total',data=df,ci=None)

sns.lineplot(x='speeding',y='total',data=df,ci=None)

sns.lineplot(x='no_previous',y='alcohol',data=df,ci=None)

sns.distplot(df["total"])

sns.distplot(df["no_previous"])

sns.relplot(x='alcohol',y='total',data=df,hue="speeding")

sns.relplot(x='total',y='no_previous',data=df)

sns.relplot(x='total',y='not_distracted',data=df,hue="speeding")

sns.relplot(x='ins_premium',y='ins_losses',data=df)

sns.relplot(x='no_previous',y='total',data=df)

sns.relplot(x='speeding',y='total',data=df)

df["speeding"].value_counts()

sns.barplot(data=df,x='not_distracted',y='total')

sns.jointplot(x="alcohol",y="not_distracted",data=df)

sns.jointplot(x="alcohol",y="total",data=df)

sns.jointplot(x="no_previous",y="not_distracted",data=df)

sns.boxplot(x="alcohol",y="speeding",data=df)

sns.boxplot(x="alcohol",y="no_previous",data=df)

sns.boxplot(x="not_distracted",y="total",data=df)

corr = df.corr()
corr

sns.heatmap(corr,annot=True)